global using CM.Domain.Checkables;
global using CM.Domain.CheckLists;
global using CM.Domain.Cqrs;
global using CM.Domain.Users;
global using CM.LiteDB;
global using FluentAssertions;
global using LiteDB;
global using Microsoft.Extensions.DependencyInjection;
global using Xunit;
