global using CM.Domain.Checkables;
global using CM.Domain.Checkables.Queries;
global using CM.Domain.CheckLists;
global using CM.Domain.CheckLists.Queries;
global using CM.Domain.Cqrs;
global using CM.Domain.Users;
global using CM.Domain.Users.Queries;
global using LiteDB;
global using System.Linq;
